#!/bin/sh
. $HOME/.i3/bar_config

ws(){ 
	ws=$(xprop -root _NET_CURRENT_DESKTOP | awk '{print $3}')
 	
	#ws=$(i3-msg -t get_outputs | sed 's/.*"current_workspace":"\([^"]*\)".*/\1/')
	#echo "%{F$FG}${ws}"

  	if [[ $ws = 0 ]]; then 
		echo "Home"
	else
		(( ws = ws + 1))
		echo $ws
	fi

	#echo $ws
}

song(){
	song=$(mpc current)
	echo $song
}

battery(){
	batt=$(acpi -b | awk -F, '{print $2 }')
	echo "Battery" $batt
}

#messy
volume(){
	vol=$(amixer -D pulse | head -n 6 | tail -n 1 | awk '{print $5}')
	isOn=$(amixer -D pulse | head -n 6 | tail -n 1 | awk '{print $6}')	
	
	echo "Volume" $vol $isOn
}

kblay(){
	LAYOUT=$(setxkbmap -query | awk '/layout/{print $2}')
	echo $LAYOUT
}

clock(){ 
	clock=$(date "+%b %d %Y %H:%M")
  	echo $clock
}



while :; do

 [[ loops -eq 15 ]] && loops=0
 [[ loops -eq 0 ]] 
 loops=$(( loops + 1 ))

 	echo "%{B#7A8A5D} $(ws) %{B-} %{F#BD6B6B} $(song) %{c}%{F#A1B67B} $(clock) %{F-} %{r}%{B#955252} $(battery) %{B-}%{B#7C5971} $(volume) %{B-}%{B#7A8A5D} $(kblay) %{B-}"

         sleep 0.5	
		 
 done | lemonbar -g ${PW}x${PH}+${PO}+${PO} -f "$FONT1"  -B "$BG" -F "$FG" -d -p | \
	while read line; do eval "$line"; done &

