#!/bin/sh

# ObliviousGmn, June 2015
# https://github.com/ObliviousGmn
# Panel for Lemonbar ..

. $HOME/.i3/bar_config

ws(){ # Current Workspace .. 
	ws=$(xprop -root _NET_CURRENT_DESKTOP | awk '{print $3}')
  
  	#if [[$ws == "0"]]; then 
	#	echo "Home"
	#else
	#	echo $ws
	#fi

	echo $ws
}

battery(){
	batt=$(acpi -b | awk -F, '{print $2}')
	echo "Battery" $batt
}

#messy
volume(){
	vol=$(amixer -D pulse | head -n 6 | tail -n 1 | awk '{print $5}')
	isOn=$(amixer -D pulse | head -n 6 | tail -n 1 | awk '{print $6}')	
	
	echo "Volume" $vol $isOn
}

kblay(){
	LAYOUT=$(setxkbmap -query | awk '/layout/{print $2}')
	echo $LAYOUT
}

clock(){ # Clock, obv ..
  clock=`date "+%b %d %Y %I:%M"`
	echo "%{F$BBLUE}  %{F-} ${clock}"
}



while :; do

 # Run ping in intervals ..
 [[ loops -eq 15 ]] && loops=0
 [[ loops -eq 0 ]] 
 loops=$(( loops + 1 ))

 	echo "%{B#7A8A5D} $(ws) %{B-} %{c}$(clock) %{r}%{B#955252} $(battery) %{B-}%{B#7C5971} $(volume) %{B-}%{B#61878B} $(kblay)  %{B-}"

         sleep 0.5	
		 
 done | lemonbar -g ${PW}x${PH}+${PO}+${PO} -f "$FONT1"  -B "$BG" -F "$FG" -d -p | \
	while read line; do eval "$line"; done &

