#!/bin/bash

SW=`xrandr | grep current | awk '{print $8}'`

# Fonts
FONT1="-xos4-terminus-medium-r-normal--16-160-72-72-c-80-iso10646-1"

# Icons ..
ICON1="-misc-stlarch-medium-r-normal--10-100-75-75-c-80-iso10646-1"
ICON2="-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1"

# Bedtime
ZZZ=12
zzz=4

# Panel
PW=$(( $SW - 20 ))
PH=26
PO=10

# Lemonpop
LW=220
LH=26
LX=1690
LY=45


# Fetch the Colors
BG="#474848"
FG="#FFF4E8"

BLACK="#2d2d2d"
BBLACK="#545454"

RED="#955252"
BRED="#BD6B6B"

GREEN="#7A8A5D"
BGREEN="#A1B678"

YELLOW="#C49D4E"
BYELLOW="#FFCC66"

BLUE="#61878B"
BBLUE="#60B1B7"

MAGENTA="#7C5971"
BMAGENTA="#A77899"

CYAN="#679787"
BCYAN="#7CB6A3"

WHITE="#f0f0f0"
BWHITE="FFF4E8"

